const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    SWITCH_LANGUAGE_OF_WEBSITE: 'SWITCH_LANGUAGE_OF_WEBSITE',
    //user,
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY: 'FETCH_ELITE_DOCTORS_VALUE_SUCCESSFULLY',
    FETCH_ELITE_DOCTORS_VALUE_FAILED: 'FETCH_ELITE_DOCTORS_VALUE_FAILED',
})

export default actionTypes;